[package]
name = "tsk-rs"
version = "0.1.0"
edition = "2021"
authors = ["Antti Peltonen <antti.peltonen@iki.fi>"]
description = "A task manager"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
bat = { version = "0.22.1", default-features = false, features = ["regex-fancy"] }
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "4.0.11", features = ["derive"] }
cli-table = "0.4.7"
config = "0.13.2"
directories = "4.0.1"
edit = "0.1.4"
file-lock = "2.1.6"
glob = "0.3.0"
hhmmss = "0.1.0"
nom = "7.1.1"
question = "0.2.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
simple-file-rotation = "0.3.4"
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.37"
toml = "0.5.9"
uuid = { version = "1.1.2", features = ["v4", "serde"] }

#eof
