[package]
name = "tsk-rs"
version = "0.1.0"
edition = "2021"
authors = ["Antti Peltonen <antti.peltonen@iki.fi>"]
description = "A task manager"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.2", features = ["derive"] }
cli-table = "0.4.7"
config = "0.13"
directories = "4.0"
file-lock = "2.1.6"
glob = "0.3.0"
nom = "7.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"
toml = "0.5.9"
uuid = { version = "1.1", features = ["v4", "serde"] }
