#
# example configuration file for tsk-rs suite
#

[data]
path = "test_data"          # if uncommented defaults to users data directory in the os e.g $HOME/.local/share/tsk-rs
#createdir = true           # if false data directory needs to exists or we exit with an error. if true directory is created
#rotate = 3                 # keep X occurances of all data files present as backups
#archivebackups = false     # when pruning data files archive the backup files
#delbackups = true          # when pruning data files delete backup files automatically

#[note]
#description = true         # if false does not add '# description' header to Markdown on edit
#timestamp = true           # if false does not add current date and time to Markdown on edit

#[task]
#autorelease = true         # if false then if task has a special tag "hold" set it is left in place
#starttag = true            # if false then special tag "start" has no effect when new task is created
#specialvisible = true      # if false then special tags are not visible in task listings
#stopondone = true          # if false then when task is marked done possible time tracking is not stopped first
#clearpsecialtags = true    # if false then when task is marked done all special tags are left in place

#[output]
#colors = true              # colorize task and note outputs
#grid = true                # draw a box around output
#numbers = true             # show line numbers in output
#namespace = true           # make namespace visible during execution
#descriptionlength = 60     # maximum number of characters to show in listings for description before it is truncated
#totals = true              # show total number of entries in listings

# eof
